print("prabhakar\nprasu")
print("----------------------------")
print("prabhakar\tprasu")
print("----------------------------")
#print("prabhakar"prabha"prasu" )(error)
print('''Hi\n This is penchala\tprabhakr From Ap''')
print("----------------------------")
print("s@athya\"Techonlogy\"")
print("----------------------------")
print("Heloo 'Prasu' Iam sharing my \"python meterial\" Check once "
      "\nIn this\tyear i get a \"job\" ")
print("----------------------------")
print("Prabhakar@0415"+"123456789")
print("----------------------------")
print(20%3)
print("----------------------------")
print("10"+"20")
print("----------------------------")
print("prabhakar","prasu",'BestFriends','''From school standerd to Still know''')
print("----------------------------")
print("python""-""Django")
print("----------------------------")
print("\n","Employee","_","UnEmployee")
print("----------------------------")
#print("prabhakar"+3)
print("3+3+""Prabahakar")
print("----------------------------")
#print("7"-2)
print("----------------------------")
print("Prabhakar\n\t\"Penchala")
print("----------------------------")
print("----------------------------")
print("**\"prabha\"kar**")
print("\n--python--")
print("----------------------------")
print("\t\tPrabhakar\tpydi")
print("\t\t==========\t====")
print("----------------------------")
studentname='Prabhakar'
print("welcome",studentname)
print("----------------------------")
#o1=int(input("Enter first number:"))
#no2=int(input("Enter second number:"))
#print("adition=",no1+no2)
#print("sub=",no1-no2)
#print("mul=",no1*no2)
#print("div=",no1/no2)
#print("mod=",no1%no2)
#print("FlorDiv=",no1//no2)
#print("Exponential=",no1**no2)
#print("----------------------------")
#x='prabha.415'
#print(x)
#print(type(x))
print("----------------------------")
#Fname=input("Enter first name:")
#Lname=input("Enter last name:")
#print(Fname + Lname)
print("----------------------------")
#x=input("Enter no:")
#print(x)
#idno=int(input("Student IDNO:"))
#name=input("Name:")
#m1=int(input("marks1:"))
#m2=int(input("marks2:"))
#m3=int(input("marks3:"))
#print(idno)
#print(name)
#print("Total marks=",m1+m2+m3)
#print("Avgmarks=",m1+m2+m3/3)
print("----------------------------")
x=5
if x>0:
      print("+ve number")
if x<0:
      print("-ve number")
print("----------------------------")

